Компонент лидерборд
22-team-007/game-crocodile pull request #13
Opened 2023-02-10 07:22 UTC by sgp900

1. Реализация компонента "доска лидеров"
2. Подключение лидерборда к api

![image](https://user-images.githubusercontent.com/76275676/218028186-1b7f7eef-0e91-4c00-b2b1-4d4417f21e9f.png)

2023-02-10 10:21 UTC, ZinovNikita requested changes
Зачем вообще подключил API, в данной задаче необходимо было просто сделать верстку.
подключение API запланировано в отдельной задаче после внедрения API .
в отдельной задаче 22-52.
Убери все API, и убери грязные изменения

2023-02-10 10:21 UTC, ZinovNikita commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +import './style.scss'
импортируй просто `import api from '../../api'`
и используй везде `api.users.get()`

2023-02-10 10:21 UTC, ZinovNikita commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +  const apiRes = new ApiRes()
объявляя через new ты объявляешь каждый раз новый экземпляр.
для этого и создан index.ts в api

2023-02-10 10:21 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +declare type ProfileParams = Omit<UserType, 'id'>
очень грязно, зачем из-за кавычек делать изменение

2023-02-10 10:21 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +  [k: string]
также очень грязно

2023-02-10 11:22 UTC, sgp900 commented on packages/client/src/types.d.ts
> +declare type ProfileParams = Omit<UserType, 'id'>
Согласен, видимо это работа претиера

2023-02-10 11:26 UTC, sgp900 commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +  const apiRes = new ApiRes()
![image](https://user-images.githubusercontent.com/76275676/218081330-23e02855-0e73-4ca2-9d25-aa3afdd058d3.png)

2023-02-10 11:26 UTC, ZinovNikita approved these changes
не стоит делать стилистические изменения в packages/client/src/types.d.ts
пусть там будет так как было, если не добавляются какие-то твои правки.

если так будут  с ' на " будут гонять и пробельчики добавлять, ничего хорошего не будет.

2023-02-10 11:28 UTC, ZinovNikita commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +  const apiRes = new ApiRes()
для этого отдельная задача вынесена специально, для внедрения всего API

2023-02-11 21:21 UTC, Vladimir556 approved these changes

2023-02-13 07:34 UTC, Brarion requested changes
Расскажите про типы

2023-02-13 07:34 UTC, Brarion commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +          )}
Условный рендеринг не подходит? В смысле без тернарника, а с `&&`

2023-02-13 07:34 UTC, Brarion commented on packages/client/src/interfaces/interfaces.ts
> +  title: string
Не могу понять, почему типы пропсов описываются не рядом с компонентом, которому они соответствуют?

2023-02-13 07:51 UTC, ZinovNikita commented on packages/client/src/pages/leaderBoard/LeaderBoard.tsx
> +          )}
@sgp900 имеется ввиду `{condition===true && <component>}`

2023-02-13 07:55 UTC, ZinovNikita commented on packages/client/src/interfaces/interfaces.ts
> +  title: string
обсуждали данную проблему, вопрос будет учтен в следующих задачах по унификации компонентов, сейчас разработчики завели компоненты, одинаковые которые имеют разные названия, но одну или похожую структуру.
унификация типов будет еще оптимизирована в будущих задачах, после слияния основных компонентов и внедрения API. чтобы было возможно учесть все.

2023-02-13 08:26 UTC, sgp900 commented on packages/client/src/interfaces/interfaces.ts
> +  title: string
Пока, если это не критично, решено в пользу единообразия, оставить как есть.

2023-02-13 12:17 UTC, Brarion approved these changes
Раз уж дальше – больше, то тут аппрув)

2023-02-13 15:22 UTC, merged