добавил редакс
22-team-007/game-crocodile pull request #20
Opened 2023-02-17 12:02 UTC by CyberDasein

### Какую задачу решаем
Добавить redux

### Что сделано
Добавил хуки useAppDispatch и useAppSelector, их нужно использовать вместо обычных (для ts) чтобы изменять/получать стор. Сделал получение данных для профиля уже из редакса, которые кладутся туда после логина. hoc WithAuth теперь проверяет наличие юзера (залогинен ли) уже из хранилища

### Что планируется сделать
Сделать поля для хранения очков игры/сообщений в сторе

2023-02-17 13:39 UTC, Vladimir556 commented on packages/client/src/pages/login/Login.tsx
> +      dispatch(usertActions.setUSer(r))
думаю лучше назвать `result` или `resonce`, а то долго втыкал что такое `r`

2023-02-17 13:42 UTC, Vladimir556 approved these changes
В целом все классно, называй переменные только подлиннее, а не одним символом :)

2023-02-17 13:48 UTC, ZinovNikita commented on packages/client/src/main.tsx
> +// api.auth.signIn({
да удалит сразу можно

2023-02-17 13:48 UTC, ZinovNikita commented on packages/client/src/pages/login/Login.tsx
> +      dispatch(usertActions.setUSer(r))
лучше user или типа того, тк там возвращается инфо о пользователе

2023-02-17 13:48 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +  value?: string
отключи у себя этот линтер, а то лишние грязные правки постоянно появляются.

2023-02-20 06:56 UTC, Brarion requested changes
В целом хорошо, но пару мест под вопросом

2023-02-20 06:56 UTC, Brarion commented on packages/client/src/interfaces/interfaces.ts
> +    user: UserType
А почему не написать просто `User` вместо `UserType`?

2023-02-20 06:56 UTC, Brarion commented on packages/client/src/main.tsx
> +// api.auth.signIn({
➕

2023-02-20 06:56 UTC, Brarion commented on packages/client/src/pages/login/Login.tsx
> +      dispatch(usertActions.setUSer(r))
➕

2023-02-20 06:56 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +    let userId = useAppSelector(state => state.userData.user?.id)
Так по задаче нужно сделать? Просто странно хранить информацию, необходимую для проверки логина в сторе, потому что при обновлении он чистится же. В `localStorage` логичнее, ведь он не чистится при обновлении страницы

2023-02-20 07:59 UTC, CyberDasein commented on packages/client/src/hoc/withAuth.tsx
> +    let userId = useAppSelector(state => state.userData.user?.id)
Да, согласен, переделаю на локалстор

2023-02-21 09:51 UTC, CyberDasein commented on packages/client/src/interfaces/interfaces.ts
> +    user: UserType
UserType уже используется много где (7 файлах), например в типизации api, не думаю что теперь стоит везде переименовывать

2023-02-21 10:46 UTC, CyberDasein commented on packages/client/src/hoc/withAuth.tsx
> +    let userId = useAppSelector(state => state.userData.user?.id)
Связал локалстор и редакс стор с помощью redux-persist в правках

2023-02-21 11:08 UTC, Brarion commented on packages/client/src/interfaces/interfaces.ts
> +    user: UserType
Это не критично, но на будущее, если вдруг надо будет по всему проекту менять что-то, в IDE разных есть функция "рефактор", там можно просто поменять название метода, функции, переменной, типа и всего, что хочешь

2023-02-21 12:36 UTC, Brarion approved these changes

2023-02-21 13:06 UTC, ZinovNikita approved these changes

2023-02-21 15:46 UTC, merged