Feature/22 50 Сделать вид менее ужасным
22-team-007/game-crocodile pull request #22
Opened 2023-02-18 11:45 UTC by sgp900

Добавлен SVG фон

Сделано выравнивание по высоте так, как это на форме регистрации и входа.

Обернул форум, форму регистрации и входа в <Card>

Сделать для класса card тень
![image](https://user-images.githubusercontent.com/76275676/219863845-2e9ee289-d417-4502-b19d-644298329728.png)

2023-02-18 14:00 UTC, ZinovNikita requested changes
в формах авторизации, регистрации и профиле сделать единую структуру footer header, остальное вкусовщина

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/layouts/app/app.scss
> +  background-size: cover;
еще background-position: center;

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/layouts/app/app.scss
> +  padding: 1.5rem;
предлагаю убрать padding

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/pages/registration/Registration.tsx
> +          <Card.Title>
предлагаю заголовок указать в card-header, либо в профиле сделать так же как тут

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/pages/registration/Registration.tsx
> +            <NavLink to={`/${Routes.Login}`}>
а кнопки в card-footer, либо в профиле сделать так же как тут

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/pages/startPage/style.scss
> +  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1600 900'%3E%3Cdefs%3E%3ClinearGradient id='a' x1='0' x2='0' y1='1' y2='0' gradientTransform='rotate
нравится идея сделать такой рисунок, предлагаю только его правее как-то расположить, а то кажется, что справа пусто как-то

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/pages/login/Login.tsx
> +          <Card.Title>
заголовок в card-header, либо в профиле сделать так же как тут

2023-02-18 14:00 UTC, ZinovNikita commented on packages/client/src/pages/login/Login.tsx
> +            <Button className='w-100 mt-3' type='submit'>Войти</Button>
кнопки в card-footer, либо в профиле сделать так же как тут

2023-02-18 14:03 UTC, ZinovNikita commented on packages/client/src/pages/startPage/style.scss
> +  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1600 900'%3E%3Cdefs%3E%3ClinearGradient id='a' x1='0' x2='0' y1='1' y2='0' gradientTransform='rotate
1920х1080 вот так выглядит, может поиграть с позицией и рамером
![image](https://user-images.githubusercontent.com/18033991/219869974-36d7534d-9350-40fd-99f0-790a1d639273.png)

2023-02-19 15:56 UTC, ZinovNikita approved these changes
Отлично

2023-02-20 06:49 UTC, Vladimir556 approved these changes

2023-02-20 07:43 UTC, Brarion commented
Описание не дописано будто "Обернул форум, форму регистрации и входа в ..."

2023-02-20 07:47 UTC, Brarion requested changes
Вынесите `svg-шки` в отдельные файлы

2023-02-20 07:47 UTC, Brarion commented on packages/client/src/layouts/app/app.scss
> +  background-attachment: fixed;
Это можно вынести в отдельный факлик, а его уже сюда импортировать с помощью `url('../*/yourAwesomSvg.svg')`

2023-02-20 07:47 UTC, Brarion commented on packages/client/src/pages/game/styles.scss
>    max-width: 1024px !important;
Не очень хорошая практика использовать `!important`, в будущем было бы супер, если бы вы убрали их

2023-02-20 07:47 UTC, Brarion commented on packages/client/src/pages/startPage/style.scss
> +  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1600 900'%3E%3Cdefs%3E%3ClinearGradient id='a' x1='0' x2='0' y1='1' y2='0' gradientTransform='rotate
Аналогично вышеупомянутому `background-image`

2023-02-20 10:10 UTC, Brarion approved these changes
Красивое)

2023-02-20 13:06 UTC, merged