Feature/22 16
22-team-007/game-crocodile pull request #3
Opened 2023-02-03 14:15 UTC by ZinovNikita

### 22 16 Профиль
- сверстать страницу
- компонент аватарки и возможность изменения
- изменение пароля

2023-02-03 15:18 UTC, Vladimir556 requested changes
Компоненты сделаны хороршо и оптимизированы. Исправь небольшие замечания указанные в комментариях и будет принято

2023-02-03 15:18 UTC, Vladimir556 commented on packages/client/src/components/Avatar.tsx
> +export default Avatar
раз мы используем ES6 синтаксис думаю лучше будет объявлять компоненты стрелочной функцией, также если у компонента больше 1 пропса делать для них интрефейс.
```
import { ChangeEvent, FC } from 'react'
import { Form, Image } from 'react-bootstrap'

interface AvatarProps {
  src: string;
  setValue: (key: string, value: string) => void;
}

const Avatar: FC<AvatarProps> = ({src, setValue}) => {
  const selectAvatar = (e: ChangeEvent<HTMLInputElement>) => {
    //upload by API
    fetch(`/`).then(() => {
      setValue(e.target.id, `https://thispersondoesnotexist.com/image?q=${new Date().getTime()}`)
    })
  }
  return <Form.Group controlId="avatar" className="mb-3">
    <Form.Label className="avatar-edit">
      <Image src={src}/>
      <Form.Control onChange={selectAvatar} type="file" accept="image/*"/>
    </Form.Label>
  </Form.Group>
}

export default Avatar
```

2023-02-03 15:18 UTC, Vladimir556 commented on packages/client/src/pages/profile/Profile.tsx
> +  }
Желательно отделять методы хотя-бы одним знаком пустой строки, другие программисты могут впасть в ступор при виде такой стены кода :)

2023-02-03 15:18 UTC, Vladimir556 commented on packages/client/src/pages/profile/Profile.tsx
> +  const [fields, setFields] = useState({} as Record<string, string>)
такие хуки могут принимать тип в generic
вот так: 
```
const [fields, setFields] = useState<Record<string, string>>({})
```

2023-02-04 08:45 UTC, CyberDasein approved these changes

2023-02-06 01:12 UTC, Vladimir556 approved these changes

2023-02-06 20:23 UTC, Brarion commented on packages/client/src/App.tsx
> +import ProfilePage from './pages/profile/Profile';
Лучше импорты разделить на следующие блоки, разделенные отступами:
1. Библиотеки
2. Всё, кроме библиотек и стилей
3. Стили

Также лучше импорт сократить до `import { ProfilePage } from './pages'`

2023-02-06 20:24 UTC, Brarion commented on packages/client/src/client.d.ts
> +}
Не уверен, что лучше хранить это в `client.d.ts`, лучше в отдельном не `.d.ts` файле

2023-02-06 20:24 UTC, Brarion commented on packages/client/src/index.scss
> +    input[type="file"]{
Советую отступы между селекторами делать, красивее будет

2023-02-06 20:25 UTC, Brarion commented on packages/client/src/main.tsx
>  import 'bootstrap/dist/css/bootstrap.min.css';
Отступы между блоками импортов смотрелись бы красиво

2023-02-06 20:26 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +import Avatar from '../../components/Avatar'
Можно сократить до `import { Avatar } from '../../components'`

2023-02-06 20:26 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +  const [page, setPage] = useState('ProfileShow')
Лучше состояние описывать в самом верху компонента

2023-02-06 20:27 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +  const switchPage = useMemo(() => {
Можно вынести в простую константу выше компонента или в файл `constants.ts`

2023-02-06 20:28 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +            return (<Form.Group key={"edit-group-"+i} controlId={e.name} className="mb-3">
Лучше не ориентироваться на `index` для `key` , можно же выбрать `e.label`

2023-02-06 20:29 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +          fieldsInput.map((e: Record<string, string>, i: number) => {
А зачем тут `Record<string, string>`? тип же сам определится на основе `fieldsInput`

2023-02-06 20:30 UTC, Brarion commented on packages/client/src/pages/profile/Profile.tsx
> +function Profile() {
Думаю, вместо кучи `switch-case` можно сделать несколько компонентов-форм, а управлять ими с помощью `react-router-dom` или состояния с каким-нибудь `enum` вместо конкретных строк

2023-02-07 06:36 UTC, ZinovNikita commented on packages/client/src/pages/profile/Profile.tsx
> +  const switchPage = useMemo(() => {
switchPage внутри использует методы, которые объявлены внутри компонента - отправка форм, обработчики кнопок итд. Если выносить в отдельную константу, то там будет неудобный перечень аргументов функции, т.е. их нужно все будет передавать туда. Думаю если как-то оптимизировать, то лучше объединить switchPage и switchButton в один метод.

2023-02-07 09:31 UTC, Brarion requested changes
Хорошая работа

2023-02-07 09:31 UTC, Brarion commented on packages/client/src/pages/profile/index.tsx
> +    }
Слишком много всего в 1 компоненте, компонент `Profile` отвечает и за формы, надо подумать, как лучше разделить формы и сам профиль. Я бы отказался от массива `fieldsInput`, и в каждой форме отдельно прописал бы все инпуты. Просто если представить, что дальше ещё будет разная логика работы с формой (интергация и валидация), компонент превратится в кашу скорее всего

2023-02-07 11:45 UTC, ZinovNikita commented on packages/client/src/pages/profile/index.tsx
> +    }
не согласен, предложенная реализация будет хуже, привожу обоснования:
1. увеличение кода раз в 5
2. этот код будет однотипный, для каждого инпута,, что противоречит DRY
3. не удастся реализовать текущий дизайн, где форма находится отдельно, а кнопки находятся отдельно, либо придется делать 3 одинаковых компонента, что также противоречит DRY
4. аргументация, что внедрение валидации превратит компонент в кашу, безосновательно, проверку также можно разместить в цикле `fieldsInput`, при вызове editField, выполнять проверку.

Таже, хочу заметить, что компонент реализован единым именно для того, что бы при изменении данных, они сразу применялись на форме просмотра и обновляя страницу тоже производилось изменение везде.

Считаю текущее решение оптимальным с точки зрения объема кода, сложности и понимания других разработчиков.

Валидация будет основана на компоненте из соседней ветки, где по факту для каждого поля прописан RegExp, который проверяет match, что фактически является однотипным решением, и может быть вынесено в параметризированный массив, и построение формы производить через цикл.

![image](https://user-images.githubusercontent.com/18033991/217235780-51e500cf-b3d8-4b55-8ce9-89b19c111b66.png)

2023-02-07 13:00 UTC, Brarion commented on packages/client/src/pages/profile/index.tsx
> +    }
В данном случае увеличение кода приведёт к лучше читаемости функционала. Пусть лучше будет больше кода, но другие разработчики поймут ваш код сразу, как только увидят
DRY хорош в теории, на практике же иногда лучше нарушить этот принцип
Не совсем понимаю, почему невозможно реализовать дизайн. Если выделить формы отдельно, всё будет логично и структурировано, сейчас же формы будто зависят друг от друга
Вы говорите про DRY, но не говорите про KISS, например, я не сразу понял, что тут и как работает, это же нарушение KISS вроде -_-
У вас в `editField` будет вызов функции валидации, которая будет отвечать сразу за несколько форм. Странно, а как же разделение ответственности и всё такое?
По поводу "Таже, хочу заметить, что компонент реализован единым именно для того, что бы при изменении данных, они сразу применялись на форме просмотра и обновляя страницу тоже производилось изменение везде.". А зачем вам данные сразу менять на форме просмотра? На форме просмотра вы смотрите данные, на форме редактирования – редактируете. Если во время редактирования пользователь вернулся назад, то предыдущие данные уже хранятся. Если же пользователь изменил данные, то новые данные можно засетить в форму просмотра
"Считаю текущее решение оптимальным с точки зрения объема кода, сложности и понимания других разработчиков." – я сразу не понял, зачем вам какой-то массив `fieldsInput`, а внутри `switch-case` с компонентами, реализованными прям внутри `switch-case`
Ваш компонент-страница (Профиль) по названию говорит только о том, что он содержит только страницу профиля, внутри же мы видим `switchPage.Page`. Немного странно, что внутри страницы ещё какие-то страницы
Кроме того, ниже представлен `JSX` вашего компонента, он должен по-хорошему разработчику говорить, за что отвечает компонент, но ваш компонент отвечает и за формы
![image](https://user-images.githubusercontent.com/54863186/217251066-2119cbdb-1005-4379-b4d7-c71da8cd6dc7.png)

2023-02-07 13:27 UTC, Brarion reviewed
Просто комментарий, чтобы не отображалось, будто я не смотрел))

2023-02-07 15:14 UTC, ZinovNikita commented on packages/client/src/pages/profile/index.tsx
> +    }
услышал тебя, ок буду 5*6=30 записывать как 5+5+5+5+5+5=30

2023-02-08 12:03 UTC, Brarion requested changes
Уже намного лучше выглядит)

2023-02-08 12:03 UTC, Brarion commented on packages/client/src/types.d.ts
> +}
Зачем писать типы в `*.d.ts` файле? Только из-за того, что их не надо импортить? В большом проекте типов и интерфейсов может быть больше 1000, они все будут тут? Это не лучшее решение. Допустим, есть тип `PasswordParams`, он относится не ко всему проекту, а к конкретному месту в проекте – к форме изменения пароля, почему бы не описать этот тип прям в файле с формой или рядом с этим файлом?
Аналогично по поводу всех этих типов
Зачем в `PasswordParams` используется `[k: string]`?
В `UserType` есть ключ `display_name`, лучше использовать `camelCase`

2023-02-08 12:03 UTC, Brarion commented on packages/client/src/pages/profile/index.tsx
> +    changeButton = <Button variant="success" type="button" onClick={() => setPage(Pages.Edit)}>Изменить</Button>
А зачем это усложнение в виде `let`, `if` и подобного?
Можно же убрать это, кнопки перенести в конкретные формы, тогда код ниже:
```tsx
<Card.Body>
        <Row>
          <Col xs="12" md="6" lg="4"><Avatar src={fields.avatar} setValue={setValue}/></Col>
          <Col xs="12" md="6" lg="8">{profileForm}</Col>
        </Row>
      </Card.Body>
      <Card.Footer className="text-end">
        <Button className="me-1" type="button" onClick={() => setPage(Pages.Password)}>Сменить пароль</Button>
        {changeButton}
      </Card.Footer>
```
превратится в что-то вроде этого:
```tsx
<Card.Body>
  {page === Pages.Show && <FormShow />}
  {page === Pages.Password && <FormPassword />}
  {page === Pages.Edit && <FormEdit />}
</Card.Body>
```

2023-02-08 12:03 UTC, Brarion commented on packages/client/src/types.d.ts
> +  second_name: string,
Тут лучше `camelCase` использовать

2023-02-08 12:03 UTC, Brarion commented on packages/client/src/pages/profile/components/FormPasword.tsx
> +}
Надо отформатировать этот код, тяжело читать без отступов и переносов строк

2023-02-08 12:03 UTC, Brarion commented on packages/client/src/pages/profile/components/FormEdit.tsx
> +}
Надо отформатировать этот код, тяжело читать без отступов и переносов строк

2023-02-08 12:03 UTC, Brarion commented
Прошу не резолвить замечания самостоятельно

2023-02-08 12:54 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +}
ты не учитываешь, что это тип будет использоваться и в API.
зачем использовать camelCase, если в API  используется такой формат параметров!
https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile

2023-02-08 12:57 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +  second_name: string,
ты не учитываешь, что это тип будет использоваться и в API.
зачем использовать camelCase, если в API используется такой формат параметров!
https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile

2023-02-08 12:58 UTC, ZinovNikita commented on packages/client/src/pages/profile/components/FormPasword.tsx
> +}
все соответствует линтеру!
опиши свои требования для линтера в таком случае, чтобы ТЕБЕ было удобно,  а не мне

2023-02-08 12:58 UTC, ZinovNikita commented on packages/client/src/pages/profile/components/FormEdit.tsx
> +}
все соответствует линтеру!
опиши свои требования для линтера в таком случае, чтобы ТЕБЕ было удобно, а не мне

2023-02-08 13:05 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +}
Зачем в PasswordParams используется [k: string]? - затем, чтобы не приходилось пр обращении к переменным такого типа через
`let v: SignInParams = {/*тут все что надо*/}`
`v['login' keyof SignInParams ]`

2023-02-08 13:08 UTC, ZinovNikita commented on packages/client/src/pages/profile/index.tsx
> +    changeButton = <Button variant="success" type="button" onClick={() => setPage(Pages.Edit)}>Изменить</Button>
согласен, но это фактически не приблуда React, аналог v-if в Vue, но так красивше

2023-02-08 14:57 UTC, ZinovNikita commented on packages/client/src/pages/profile/components/FormPasword.tsx
> +}
в следующем коммите запушил промежуточный вариант, надеюсь он будет читабелен.
потому что вариант предлагаемый тобой неясен мне. мне привычнее, когда компонент ближе к стилю html

2023-02-09 10:06 UTC, Brarion commented on packages/client/src/types.d.ts
> +}
> ты не учитываешь, что это тип будет использоваться и в API. зачем использовать camelCase, если в API используется такой формат параметров! https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile

Не знал про то, что в апи такой стиль(

2023-02-09 10:08 UTC, Brarion commented on packages/client/src/types.d.ts
> +}
> Зачем в PasswordParams используется [k: string]? - затем, чтобы не приходилось при обращении к переменным такого типа через `let v: PasswordParams = {/*тут все что надо*/}` `v['oldPassword' as keyof PasswordParams]` и соответственно во всех других типах, которые основаны на этом

Хм, немного не понял тебя, я убрал `[k: string], всё работает
![Снимок экрана 2023-02-09 в 13 07 08](https://user-images.githubusercontent.com/54863186/217782094-6e455e63-aeaf-4829-a650-9a764c043582.png)

2023-02-09 10:12 UTC, Brarion commented on packages/client/src/pages/profile/components/FormPasword.tsx
> +}
Я понимаю, что у разных разработчиков вкус может быть разный, я абсолютно не против твоего решения, просто хочу сказать, что обычно используется настроенный `prettier` в паре с `eslint`  так, что всё-таки получаются лишние пробелы

2023-02-09 10:12 UTC, Brarion commented on packages/client/src/types.d.ts
> +  second_name: string,
Не знал про то, что в апи такой стиль(

2023-02-09 10:13 UTC, Brarion commented on packages/client/src/pages/profile/components/FormEdit.tsx
> +}
Аналогичный ответ, что и с паролем)

2023-02-09 10:15 UTC, Brarion approved these changes
Я аппрувнул, но напиши, пожалуйста, про [k: string], немного не понял тебя
И по поводу `index.d.ts`. Почему не перенести типы в отдельные файлы типа `types.ts` рядом с соответствующим функционалом?

2023-02-09 11:05 UTC, merged