Feature/22 69 отображение сообщений валидации
22-team-007/game-crocodile pull request #31
Opened 2023-02-26 21:43 UTC by Vladimir556

### Какую задачу решаем
отображать текст ошибки по формату полей

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/71672451/221439185-62d8ad54-fd85-4d4e-b292-e79aa80eb450.png)

### TBD (если есть)

2023-02-27 20:52 UTC, ZinovNikita approved these changes

2023-02-28 07:42 UTC, CyberDasein approved these changes

2023-02-28 09:51 UTC, Brarion requested changes
Оставил 1 замечание, но относится ко всем местам

2023-02-28 09:51 UTC, Brarion commented on packages/client/src/pages/login/Login.tsx
> +                pattern: { value: validation.login.regExp!, message: validation.login.message },
Не рекомендуется использование `!`, лучше сделать что-то вроде такого (ну или может, можно лучше придумать):
```tsx
            <FormInput
              label={'Логин'}
              isInvalid={!!errors?.login}
              register={register('login', {
                required: 'Обязательное поле.',
                pattern: validation.login.regExp ? {
                  value: validation.login.regExp,
                  message: validation.login.message
                } : undefined
              })}
              errorMsg={errors?.login?.message}
            />
```

2023-02-28 12:47 UTC, ZinovNikita commented on packages/client/src/pages/login/Login.tsx
> +                pattern: { value: validation.login.regExp!, message: validation.login.message },
Можно формирование этого объекта вынести в отдельную функцию

           {
                required: 'Обязательное поле.',
                pattern: validation.login.regExp ? {
                  value: validation.login.regExp,
                  message: validation.login.message
                } : undefined
              }

типа так

     (key)=>{
         return  {
                required: 'Обязательное поле.',
                pattern: validation[key].regExp ? {
                  value: validation[key].regExp,
                  message: validation[key].message
                } : undefined
              }
     }

2023-02-28 21:47 UTC, Vladimir556 commented
Думаю такой вариант, как в крайнем коммите будет намного лучше

2023-02-28 21:50 UTC, Vladimir556 commented
Также добавил валидацию на формы изменения пароля и профиля

2023-03-01 07:00 UTC, Brarion approved these changes
Да, выглядит симпатичнее

2023-03-01 10:12 UTC, merged