bug fix
22-team-007/game-crocodile pull request #33
Opened 2023-03-03 09:01 UTC by CyberDasein

### Какую задачу решаем
чтобы при входе и выходе сразу изменялось меню (кнопки выход/вход) и настройка доступа к приватным страницам.

2023-03-03 13:38 UTC, ZinovNikita approved these changes
хорошо

2023-03-03 18:14 UTC, Brarion requested changes
Думаю, данное решение связано с проблемой написания тестов, либо я чего-то не понял-_-

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/main.tsx
> +import { Index } from './router'
Странное название `Index`

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/router.tsx
>    }
Не понимаю, зачем тут `forTest`, то есть почему функция должна зависеть от параметров, которые используются только в тестах?
Можно же в `router.test.tsx` замокать всё аналогично тому, как сейчас в случае, если `getRouterConf` принимает аргумент, не равный пустой строке

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/router.tsx
>    }
Соответственно тогда не будет объявления `let dispatch`, у которого тип не только `(arg0: UserLogoutAction) => any`, но и `undefined` на самом деле

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/router.tsx
> +            forTest ? false : dispatch(logoutUser())
Аналогично

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/router.tsx
> +  const router = getRouterConf()
Не до конца понял, что делает эта функция, если убрать аргумент из неё, то есть она просто возвращает `routerConf`, который был и раньше? (Не считая изменений с функциями в строке `133`, Можно же сразу как константу объявить `routerConf` уже с новыми функциями, после чего можно избавиться в целом от компонента `Index`, вернувшись немного к прошлой реализации

Если я где-то ошибаюсь, напишите

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/store/actions/types.ts
> +  payload: null
Зачем тут тогда `payload`?

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/store/actions/user.ts
> +  payload: null
Аналогично. Зачем тут тогда `payload`?

2023-03-03 18:14 UTC, Brarion commented on packages/client/src/store/actions/types.ts
> +  payload: null
Просто в редьюсере `payload` даже не используется

2023-03-04 09:12 UTC, CyberDasein commented on packages/client/src/router.tsx
>    }
@Brarion Мне нужно было выполнить хук диспатча для логаута в router.tsx. Раньше настройки роутера были объявлены через константу, и возникала ошибка что нельзя использовать хуки вне функц.компонентов. Именно поэтому я обернул конфиг и диспатч в функцию. В тестах раньше конфиг роутера импортировался как константа без этого хука, а с ним возникает эта же ошибка, поэтому для тестов сделал такую проверку, чтобы им отдавался конфиг как раньше (чтобы не переписывать тесты)

2023-03-04 09:15 UTC, CyberDasein commented on packages/client/src/router.tsx
> +            forTest ? false : dispatch(logoutUser())
Вот, тут как раз вызов диспатча вызывает ошибку в тестах, поэтому им отдаем конфиг без него

2023-03-04 09:16 UTC, CyberDasein commented on packages/client/src/router.tsx
> +  const router = getRouterConf()
Ответил выше, связано с ошибкой вызовы хука вне fc

2023-03-04 09:17 UTC, CyberDasein commented on packages/client/src/store/actions/types.ts
> +  payload: null
Да, но payload должен быть в экшене и редьюсере, без него ошибка типизации

2023-03-04 09:23 UTC, CyberDasein commented on packages/client/src/router.tsx
>    }
ну и чтобы не дублировать конфиг для тестов, не мокать его, а использовать как он есть в приложении

2023-03-04 09:59 UTC, sgp900 approved these changes

2023-03-05 13:11 UTC, Brarion commented on packages/client/src/store/actions/types.ts
> +  payload: null
Можно поиграться с типами, но скорее всего это роль не сыграет, поэтому ок

2023-03-05 13:28 UTC, Brarion commented on packages/client/src/router.tsx
>    }
@CyberDasein чёт сразу не понял. Решение применимо в целом, но я бы делал по-другому: не использовал бы вообще `route` для выхода, просто сделал бы кнопку `Выход` действительно кнопкой, так можно будет избавиться от `loader` с диспатчем, либо, если уже так хочется сделать, то `loader` на самом деле принимает ещё и `any`, значит, можно попробовать в него засунуть компонент функциональный, который будет возвращать `null` и делать всю работу сам (вызывать хуки, диспатчить и тп), но это роли большой не играет на самом деле
Окей, аппрув, но не советую в коде использовать какие-то условия только для тестов. У вас код - это рабочий код, тесты лишь должны проверять его работу, а не влиять на сам код каким-либо способом

2023-03-05 13:28 UTC, Brarion approved these changes

2023-03-06 05:18 UTC, merged