Feature/22 15
22-team-007/game-crocodile pull request #4
Opened 2023-02-03 15:38 UTC by Vladimir556

### Авторизация и регистрация

- страницы без логики
- данные можно хранить на фронте
- можно использовать API практикума

2023-02-03 17:15 UTC, ZinovNikita submitted a review, later dismissed

2023-02-03 17:15 UTC, ZinovNikita commented on packages/client/src/pages/registration/Registration.tsx
> +import { validation } from '../../utils/validation'
Предлагаю сделать index.ts в utils, в который импортировать все файлы утилит
`import { validation } from '../../utils'`

2023-02-03 17:15 UTC, ZinovNikita commented on packages/client/src/types/interfaces.tsx
> +export interface LoginData {
Предлагаю вести типы/интерфейсы в файле `client.d.ts`, чтобы не импортировать их явно.

2023-02-03 17:33 UTC, ZinovNikita submitted a review, later dismissed

2023-02-04 02:48 UTC, sgp900 approved these changes

2023-02-04 15:42 UTC, ZinovNikita requested changes
Логика компонентов реализована хорошо. Добавь указанные в комментариях предложения, чтобы получить визу

2023-02-06 03:41 UTC, Vladimir556 commented
Конфликты возникали из-за того что в ветке dev удалил компонент Login, так что временно его перемеименновал в SignIn

2023-02-06 05:07 UTC, ZinovNikita approved these changes

2023-02-06 20:07 UTC, Brarion commented on packages/client/src/types/interfaces.tsx
> +export interface LoginData {
Мне кажется, явный импорт лучше. Иначе огромное количество типов/интерфейсов в будущем будут лежать в одном `index.d.ts`

2023-02-06 20:08 UTC, Brarion commented on packages/client/src/utils/index.ts
> +export default validation;
Скорее всего экспортов будет больше, чем 1, поэтому лучше обойтись без `default`, а сделать так:
```ts
export { validation }
```

2023-02-06 20:09 UTC, Brarion commented on packages/client/src/utils/validation.ts
> +export const validation: Record<string, { regExp?: RegExp, message: string, errMessage: string }> = {
Можно вынести регулярки в константы, так объект `validation` лучше будет читаться

2023-02-06 20:11 UTC, Brarion commented on packages/client/src/components/FormInput.tsx
> +      <Form.Control.Feedback className={'mt-0'} type='invalid'>{errorMsg}</Form.Control.Feedback>
Разные форматы передачи пропсов, в `type` просто строка, а в `className` ещё в фигурные скобки обёрнуто, лучше придерживаться одного стиля

2023-02-06 20:12 UTC, Brarion commented on packages/client/src/components/FormInput.tsx
> +        type={isPassword ? 'password' : 'text'}
Результат регулярки для красоты можно вынести в переменную, например, вот так:
```tsx
const type = isPassword ? 'password' : 'text';
```

2023-02-06 20:14 UTC, Brarion commented
А где всё?)

<img width="1193" alt="Снимок экрана 2023-02-06 в 23 14 13" src="https://user-images.githubusercontent.com/54863186/217075393-9e06a34e-6426-48c4-a473-0c178f62a692.png">

2023-02-06 20:15 UTC, Brarion commented on packages/client/src/pages/login/SignIn.tsx
> +    fetch('https://ya-praktikum.tech/api/v2/auth/signin', {
Советую использовать `axios` и не использовать временные решения. Создайте папку `api`, там опишите запросы, думаю, так будет лучше

2023-02-06 20:16 UTC, Brarion commented on packages/client/src/pages/login/SignIn.tsx
> +    console.log(data)
`console.log` лишний)

2023-02-06 20:16 UTC, Brarion commented on packages/client/src/pages/login/SignIn.tsx
> +      <Form style={{width: '300px'}} noValidate onSubmit={handleSubmit(onSubmitHandler)}>
Стили лучше в `.scss` вынести или в `.css`, смотря, что используете

2023-02-06 20:18 UTC, Brarion commented on packages/client/src/pages/login/SignIn.tsx
> +        <Button className='w-100' size='sm' variant='link'>Нет аккаунта?</Button>
`link` куда-то перенаправляет?

2023-02-06 20:19 UTC, Brarion commented on packages/client/src/pages/registration/Registration.tsx
> +  }
Аналогично комментариям к файлу `SignIn`

2023-02-06 20:19 UTC, Brarion commented on packages/client/src/pages/registration/Registration.tsx
> +      <Form style={{ width: '300px' }} noValidate onSubmit={handleSubmit(onSubmitHandler)}>
Аналогично комментариям к файлу SignIn

2023-02-06 20:19 UTC, Brarion commented on packages/client/src/pages/registration/Registration.tsx
> +        <Button className='w-100' size='sm' variant='link'>Войти</Button>
Аналогично комментариям к файлу SignIn

2023-02-08 14:57 UTC, Vladimir556 commented on packages/client/src/pages/login/SignIn.tsx
> +        <Button className='w-100' size='sm' variant='link'>Нет аккаунта?</Button>
т.к роутер еще не готов, то никуда. В дальнейшем будет линк на registration

2023-02-08 15:07 UTC, Vladimir556 commented on packages/client/src/pages/login/SignIn.tsx
> +    fetch('https://ya-praktikum.tech/api/v2/auth/signin', {
Мы с командой договорились использовать `fetch`

2023-02-08 15:12 UTC, ZinovNikita commented on packages/client/src/pages/login/SignIn.tsx
> +    console.log(data)
Ответ ЛК: компонент в данной задаче реализуется с незавершенным функционалом, это заглушка.
Потому что функционал по реализации API и внедрение его во все компоненты запланирован в отдельных задачах

2023-02-08 15:14 UTC, ZinovNikita commented on packages/client/src/pages/login/SignIn.tsx
> +    fetch('https://ya-praktikum.tech/api/v2/auth/signin', {
Ответ ЛК: компонент в данной задаче реализуется с незавершенным функционалом, это заглушка.
Потому что функционал по реализации API и внедрение его во все компоненты запланирован в отдельных задачах

2023-02-08 15:15 UTC, ZinovNikita commented on packages/client/src/pages/login/SignIn.tsx
> +        <Button className='w-100' size='sm' variant='link'>Нет аккаунта?</Button>
Ответ ЛК: компонент в данной задаче реализуется с незавершенным функционалом, это заглушка.
Роутер реализуется в смежной задаче, которая была принята недавно ауфегку/22-14

2023-02-08 15:15 UTC, ZinovNikita commented on packages/client/src/pages/registration/Registration.tsx
> +  }
Ответ ЛК: компонент в данной задаче реализуется с незавершенным функционалом, это заглушка.
Роутер реализуется в смежной задаче, которая была принята недавно feature/22-14

2023-02-09 10:24 UTC, Brarion approved these changes
;)

2023-02-09 11:16 UTC, merged