Feature/22 74 Форум Бэкенд
22-team-007/game-crocodile pull request #40
Opened 2023-03-14 18:43 UTC by ZinovNikita

### Форум Бэкенд

созданы ручки для CRUD

создано API для работы с сервером

2023-03-16 02:31 UTC, Vladimir556 approved these changes
👍

2023-03-16 02:31 UTC, Vladimir556 commented on packages/client/src/types.d.ts
> +}[]
EOF ошибка, в будущем нужно будет линтер запустить

2023-03-16 05:22 UTC, CyberDasein approved these changes

2023-03-16 07:54 UTC, Brarion requested changes

2023-03-16 07:54 UTC, Brarion commented on packages/server/controllers/ForumController.ts
> +  await dbConnect()
`dbConnect` судя по названию подключается к БД, но зачем это делать в контроллере? То есть если у вас будет `N` контроллеров, то и подключений будет N?

2023-03-16 07:54 UTC, Brarion commented on packages/server/controllers/ForumController.ts
> +  })
Относится ко всем "ручкам", странно, что ваш метод контроллера делает сразу и запрос к базе, и логику. То есть было бы круто разделить на сервисы, репозитории и обычные контроллеры
Первое попавшееся в интернете по структуре express – https://nodejsdev.ru/guides/webdraftt/app-structure/

2023-03-16 07:54 UTC, Brarion commented on packages/server/index.ts
> +  await ForumController(app)
Выше приложил ссылку, там про роутинг тоже есть, с помощью которого красивее можно сделать

2023-03-16 07:54 UTC, Brarion commented on packages/client/src/api/forum.ts
> +    record.id = 0
А зачем при создании прописывать `id`? Без него нельзя?

2023-03-16 07:54 UTC, Brarion commented on packages/client/src/api/forum.ts
> +    record.id = 0
Ну то есть при создании вы же не знаете `id`, его ещё нет, потому что записи в БД ещё нет, соответственно при создании не отправляют такое поле

2023-03-16 07:54 UTC, Brarion commented on packages/client/src/api/forum.ts
> +    const r = await this.POST(`/forum/${id}`, {
Не совсем понимаю, в чём смысл `record` и `id` как отдельных параметров? Почему нельзя сразу в функцию эту отправить уже корректный объект?
Ниже аналогично

2023-03-16 09:30 UTC, ZinovNikita commented on packages/client/src/api/forum.ts
> +    record.id = 0
метод создания и редактирования имеет один интерфейс - создание если id=0, редактирование, если id!=0

2023-03-17 07:55 UTC, ZinovNikita commented on packages/server/controllers/ForumController.ts
> +  })
`import { dbConnect, ForumRecord, sequelize } from '../db'`
в данном случае мы используем sequelize, и ForumRecord выступает как сервис (модель), который я вызываю из контроллера. также как в примере по ссылке.

согласен, dbConnect нужно вынести в общий метод и передавать параметром

2023-03-17 07:56 UTC, ZinovNikita commented on packages/server/index.ts
> +  await ForumController(app)
согласен, описать в том формате лучше, думаю также внутрь api это добавить

2023-03-17 07:57 UTC, ZinovNikita commented on packages/client/src/api/forum.ts
> +    const r = await this.POST(`/forum/${id}`, {
думаю сделать женерик для входных параметров

2023-03-19 11:12 UTC, Brarion approved these changes

2023-03-20 07:05 UTC, merged