Feature/22 31
22-team-007/game-crocodile pull request #44
Opened 2023-03-23 06:09 UTC by Vladimir556

### Какую задачу решаем
## Форум (API)
- Добавить возможность получить список комментариев, создавать и удалять посты, добавлять к постам реакции (требует дальнейшей декомпозиции)

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/71672451/227118306-d236241c-cb19-483e-9cb9-87ed8c7fba25.mp4

### TBD (если есть)

2023-03-23 22:22 UTC, ZinovNikita commented on packages/client/src/pages/forum/components/MessageToolbar.tsx
> +import svgB from './../../../assets/msgToolbar/format_bold.svg'
Может рассмотреть https://fontawesome.com/docs/web/use-with/react/
или через cdn его как-то внедрить?
это было бы полезно и для других иконок, используемых у нас

2023-03-23 22:22 UTC, ZinovNikita commented on packages/client/src/types.d.ts
> +  id?: number
я изменил метод api в своей ветке задав тип `Omit<ForumRecord, 'id'>` в создании.
думаю, лучше также сделать, а id обязательное должно быть

2023-03-23 22:22 UTC, ZinovNikita commented on packages/server/controllers/ForumController.ts
>  class ForumController {
я изменил в своей ветке, что конкретно не работает? я там разделил ручки создания и изменения и комментария и темы.
но само api абстрактное и не зависит от ручек. в моих проверках он создавал все верно и в старой и в новой версии с докером

2023-03-26 06:14 UTC, Vladimir556 commented on packages/server/controllers/ForumController.ts
>  class ForumController {
Хорошо, я тогда сделаю мердж с твоей веткой, и протестирую как фронт работает с новыми ручками

2023-03-26 06:14 UTC, Vladimir556 commented on packages/client/src/pages/forum/components/MessageToolbar.tsx
> +import svgB from './../../../assets/msgToolbar/format_bold.svg'
Да, было бы удобнее

2023-03-26 08:24 UTC, ZinovNikita approved these changes
Исправь ошибку деплоя версаль и согласовано

2023-03-27 09:19 UTC, CyberDasein approved these changes

2023-03-27 15:43 UTC, Vladimir556 commented
>

2023-03-27 15:45 UTC, Vladimir556 commented
@ZinovNikita мне не нравится как в этой ветке я реализовал хуки для работы с беком, не учел колличество перерендеров, сейчас в ветке с реализацией эмоций сообщений все исправил

2023-03-28 08:32 UTC, Brarion requested changes
Давайте постараемся не делать такие большие мр'ы, максимум 500 новых строк

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/hooks/useGetForumMessages.tsx
> +  const [users, setUsers] = useState<any>({})
Не советую использовать `any`, в случае, если изначально нет пользователей, можно поставить `null | Users` или что-то вроде того, главное тут `null`

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/hooks/useGetForumMessages.tsx
> +  }
А почему это не вынесено в `useEffect` с `deps` `loading`?
Или, если это срабатывает 1 раз в самом начале, то можно вынести в `useEffect` с пустыми `deps`

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/hooks/useGetForumTheme.tsx
> +  }
Аналогично

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/hooks/useGetForumThemes.tsx
> +  }
Аналогично

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/pages/forum/components/MarkDown.tsx
> +            // @ts-ignore
А можно избавиться от `@ts-ignore`?

2023-03-28 08:32 UTC, Brarion commented on packages/client/src/pages/forum/components/MessageForm.tsx
> +      }
Настолько большой `switch-case`, что хочется его вынести в отдельный файл

2023-04-04 02:12 UTC, closed without merging