Feature/22 76
22-team-007/game-crocodile pull request #47
Opened 2023-03-27 18:59 UTC by Vladimir556

### Какую задачу решаем
реализовать реакции на комментраии на подобие как сделано в гите
также оптимизация хуков для работы с бэком форума

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/71672451/228040163-0f6c6d97-2183-4e0c-ab48-dde3d12dd815.mp4

### TBD (если есть)

2023-04-04 05:14 UTC, CyberDasein approved these changes

2023-04-04 07:08 UTC, Brarion requested changes
Я уже не 1ый раз пишу, почему так много?
```diff
+1,170
```
Декомпозируйте задачу, чтобы были МРы до 500 строк

2023-04-04 08:46 UTC, ZinovNikita requested changes
довнедри fontawesome

2023-04-04 08:46 UTC, ZinovNikita commented on packages/client/src/api/forum.ts
>    public async get(id: number): Promise<ForumRecord> {
убери http://localhost:3001 - нужно запускать на 3001 порту - там сервер

2023-04-04 08:46 UTC, ZinovNikita commented on packages/client/src/pages/forum/components/ForumComments.tsx
> +
давай уж перейдем на fontawesome полностью используй эти иконки для форматирования текста  https://fontawesome.com/search?o=r&m=free&c=text-formatting&s=solid&f=classic
h1-h3 можно использовать такой html

    <font-awesome-icon icon="fa-solid fa-heading" /><sub>1</sub>
    <font-awesome-icon icon="fa-solid fa-heading" /><sup>1</sup>

вот ссылка https://fontawesome.com/icons/link?f=classic&s=solid

вот more https://fontawesome.com/icons/ellipsis?f=classic&s=solid
поиск https://fontawesome.com/icons/magnifying-glass?f=classic&s=solid
картинка https://fontawesome.com/icons/image?f=classic&s=solid
код https://fontawesome.com/icons/code?f=classic&s=solid
курсив https://fontawesome.com/icons/italic?f=classic&s=solid
подчеркнутый https://fontawesome.com/icons/underline?f=classic&s=solid
жирный https://fontawesome.com/icons/bold?f=classic&s=solid
закрыть https://fontawesome.com/icons/xmark?f=classic&s=solid

2023-04-04 08:46 UTC, ZinovNikita commented on packages/client/src/pages/forum/components/MessageToolbar.tsx
> +
тут тоже все из fontawesome подключить

2023-04-04 17:45 UTC, ZinovNikita commented
@Brarion, это по факту прошлый МР, уже с изменениями. пришлось объединить с другой веткой для решения проблемы

2023-04-04 20:44 UTC, Vladimir556 commented
@Brarion  этот ПР сделан на основе ветки 22 - 31 где было 1000+ строк поэтому так много. Здесь пофиксил все замечания которые были указаны в 22-31. Ты предлагаешь мне эту ветку Дробить на две ?

2023-04-05 19:13 UTC, Brarion approved these changes
Я не понимаю, как так получается, что прошлый МР объединён с этим
1 задача - 1 ветка - 1 МР

2023-04-05 19:13 UTC, Brarion commented on packages/client/src/hooks/useGetForumMessages.tsx
> +      })
Тут лучше замапить сразу

2023-04-10 16:35 UTC, ZinovNikita approved these changes

2023-04-11 10:59 UTC, merged