MVP роутера
22-team-007/game-crocodile pull request #5
Opened 2023-02-04 10:18 UTC by sgp900

### Какую задачу решаем
Первичная реализация (MVP) роутера.
Простой HOC для приватных страниц.

2023-02-04 15:28 UTC, ZinovNikita requested changes
Проверка авторизации и HOC компонент реализованы.
предлагаю изменить стиль главного меню и убрать лишние импорты.

2023-02-04 15:28 UTC, ZinovNikita commented on packages/client/src/App.tsx
> +        <ul className="nav nav-tabs">
Предлагаю использовать Navbar для меню https://react-bootstrap.github.io/components/navbar/

2023-02-04 15:28 UTC, ZinovNikita commented on packages/client/src/hoc/withAuth.tsx
> +import React from 'react'
Предлагаю сделать импорт только `import { ComponentType } from 'react'`

2023-02-04 15:28 UTC, ZinovNikita commented on packages/client/src/hoc/withAuth.tsx
> +  RedirectComponent: React.ComponentType<T>
Предлагаю объявлять просто вот так:
`PrivatComponent: ComponentType<P>,`
`RedirectComponent: ComponentType<T>`

2023-02-05 11:04 UTC, ZinovNikita approved these changes

2023-02-06 01:15 UTC, Vladimir556 approved these changes

2023-02-06 19:29 UTC, Brarion commented
Конфликты стоит решить (в тёмной теме комментарий выглядит, как текст с кнопкой, это скриншот на самом деле)
<img width="831" alt="Снимок экрана 2023-02-06 в 22 28 21" src="https://user-images.githubusercontent.com/54863186/217066389-b6e97e9a-ab19-4d87-b179-84f46d9d0c29.png">

2023-02-06 19:31 UTC, Brarion commented on packages/client/src/App.test.tsx
> +import { BrowserRouter as Router } from 'react-router-dom'
Лучше библиотеки переместить наверх, а остальные импорты вниз, так будет красивее. Ещё отступ между библиотеками и остальными импортами, и будет красотища)

2023-02-06 19:33 UTC, Brarion commented on packages/client/src/App.tsx
> +import { Container, Navbar, Nav } from 'react-bootstrap'
`Nav` не используется, надо бы убрать

2023-02-06 19:34 UTC, Brarion commented on packages/client/src/App.tsx
>  import './App.css'
Импорты – огонь, но комментарии лишь отвлекают

2023-02-06 19:34 UTC, Brarion commented on packages/client/src/App.tsx
> +
Что это тут делает?)

2023-02-06 19:42 UTC, Brarion commented on packages/client/src/App.tsx
> +    | undefined
Не стоит определять тип внутри компонента. Также лучше название типа с большой буквы писать. В целом тип очень странный, не совсем понятно, что он делает, пока не упадешь в исходники `className` у `<NavLink />`. Ещё не понятно, почему `getClassCbk` может быть `undefined`. И почему возвращаемое значение может быть `undefined`, если мы знаем, что там всегда будет `string` в нашем случае. Так будет получше, но можно ещё подумать:
```tsx
type GetClassCbk = (props: { isActive: boolean; isPending: boolean }) => string
```

2023-02-06 19:43 UTC, Brarion commented on packages/client/src/App.tsx
> +    const active = isActive ? 'active' : isPending ? 'pending' : ''
Тернарник в тернарнике выглядит страшно(

2023-02-06 19:43 UTC, Brarion commented on packages/client/src/App.tsx
> +    const active = isActive ? 'active' : isPending ? 'pending' : ''
И название `active` не подходит в данном случае, ведь значение может быть и `pending`

2023-02-06 19:44 UTC, Brarion commented on packages/client/src/App.tsx
> +            {/* <Nav className="me-auto"> */}
Лучше удалить комментарий, он тут лишний

2023-02-06 19:44 UTC, Brarion commented on packages/client/src/App.tsx
> +            {/* </Nav> */}
Лучше удалить комментарий, он тут лишний

2023-02-06 19:48 UTC, Brarion commented on packages/client/src/App.tsx
> +            </ul>
Лучше вынести в константный массив вроде
```ts
const LINKS = [{
  title: 'login',
  path: 'login',
}]
```
А затем написать в этом компоненте примерно так:
```tsx
<ul className="nav nav-tabs">
  {LINKS.map(link => (<li className="list-group-item" key={link.path}>
                <NavLink className={isActive} to={link.path}>
                 {link.title}
                </NavLink>
              </li>)}
</ul>
```
Сам массив можно вынести в файл `constants.ts` рядом с этим файлом

2023-02-06 19:48 UTC, Brarion commented on packages/client/src/App.tsx
> +      {<Outlet />}
А зачем тут фигурные скобки?

2023-02-06 19:49 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +  PrivatComponent: ComponentType<P>,
Думаю, тут забыта буква `e`

2023-02-06 19:50 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +  // @ts-ignore  @typescript-eslint/no-explicit-any
Эти комментарии выглядят страшно

2023-02-06 19:51 UTC, Brarion commented on packages/client/src/main.tsx
> +// import Registration from './pages/registration/Registration'
Лишние комментарии

2023-02-06 19:53 UTC, Brarion commented on packages/client/src/main.tsx
> +const ProfilePage = WithAuth(Profile, Login)
Лучше сразу вынести эти компоненты-страницы в папку `pages`

2023-02-06 19:54 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +      <RedirectComponent {...props} />
Не совсем понимаю, зачем тут `RedirectComponent`, почему бы в случае, если `login === false` не делать редирект на необходимый путь?

2023-02-06 19:59 UTC, Brarion commented on packages/client/src/pages/error/Error.tsx
> +  }
Можно дефолтную ошибку со статусом 200 (забавно) вынести в константу над компонентом. Тогда будет примерно так:
```tsx
const DEFAULT_ERROR = {
      data: null,
      status: 200,
      statusText: 'Ok',
      message: 'Ok',
    }
    
export default function ErrorPage() {
  let error = (useRouteError() as ErrorResponse) || DEFAULT_ERROR
```

Ну и раз уж `useRouteError` может возвращать `null` или `undefined` (странно, почему в исходниках тип `unknown`), то тип `ErrorResponse` может быть не только таким, какой сейчас есть, но и `null | undefined`

2023-02-06 20:00 UTC, Brarion commented on packages/client/src/main.tsx
> +import ErrorPage from './pages/error/Error'
Импорт страниц лучше сделать с помощью React.lazy

2023-02-06 20:02 UTC, Brarion commented
Пожалуйста, смотрите без звука, клавиатура громко клацает, простите(

https://user-images.githubusercontent.com/54863186/217072870-ea6f6e32-01a7-4248-beb3-07910bcb1331.mov

2023-02-07 04:19 UTC, sgp900 commented on packages/client/src/hoc/withAuth.tsx
> +      <RedirectComponent {...props} />
Думал хок должен возвращать компонент по определению. Но могу переписать.

2023-02-07 07:34 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +      <RedirectComponent {...props} />
Можно сделать вместо `<RedirectComponent />` вот такое: `<Navigate replace to={redirectTo} />`. `react-router-dom` содержит компонент `Navigate`
```tsx
import { Navigate } from 'react-router-dom'
```
И соответственно вместо `RedirectComponent` в пропсах будет `redirectTo` типа `string`

2023-02-07 08:18 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +    })
Если тут используется метод `componentDidMount`, то в `useEffect` должен быть второй аргумент `deps` в виде пустого массива:
```tsx
useEffect(() => {
      if (typeof riderectIfUser !== 'boolean') {
        riderectIfUser = false
      }

      // пока пользователь захардкожен
      const login = true

      if (login === riderectIfUser) {
        navigate(pathRedirect)
      }
    }, [])
```

2023-02-07 08:38 UTC, ZinovNikita approved these changes

2023-02-07 08:45 UTC, Brarion requested changes
Хорошая работа, небольшие недочёты остались)

2023-02-07 08:45 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +  riderectIfUser = false
Не вижу смысла в `redirectIfUser`. Думаю, временно можно было оставить `Math.random`, только вместо `useNavigate` использовать `Navigate`.
Можно сделать вместо `<RedirectComponent />` вот такое: `<Navigate replace to={redirectTo} />`. `react-router-dom` содержит компонент `Navigate`
```tsx
import { Navigate } from 'react-router-dom'
```
И соответственно вместо `RedirectComponent` в пропсах будет `redirectTo` типа string

2023-02-07 08:45 UTC, Brarion commented on packages/client/src/layouts/app/App.tsx
> +}
Пока что можно удалить это, а в месте использования `appLoader` написать просто `null`. Лучше в PR не добавлять временный или неиспользуемый код

2023-02-07 08:45 UTC, Brarion commented on packages/client/src/main.tsx
> +const GamePage = WithAuth(Game, '/' + Routes.Login, false)
Вместо этого можно прям в файлах с компонентами сделать вот так со всеми 3 страницами:
```tsx
import WithAuth from "../../hoc/withAuth"

function Game() {
  return (
    <div>
      <h1>Game Page!</h1>
    </div>
  )
}

export default WithAuth(Game)
```

2023-02-07 08:45 UTC, Brarion commented on packages/client/src/hoc/withAuth.tsx
> +    })
Если тут используется метод `componentDidMount`, то в `useEffect` должен быть второй аргумент `deps` в виде пустого массива:
```tsx
useEffect(() => {
      if (typeof riderectIfUser !== 'boolean') {
        riderectIfUser = false
      }

      // пока пользователь захардкожен
      const login = true

      if (login === riderectIfUser) {
        navigate(pathRedirect)
      }
    }, [])
```

2023-02-07 09:17 UTC, Vladimir556 approved these changes

2023-02-07 09:57 UTC, Brarion approved these changes

2023-02-07 09:58 UTC, Brarion commented
Супер, только конфликты пофиксить надо и посмотреть, что произошло в Vercel

2023-02-07 10:52 UTC, merged