доработки по игре
22-team-007/game-crocodile pull request #51
Opened 2023-04-02 16:35 UTC by CyberDasein

### Какую задачу решаем
Доработка логики игры:  переделал модальные окна, стили, добавил таймер старта на 10 сек(если игрок не успел, ход переходит к другому), добавил компонент toast для различных уведомлений, поправил передачу толщины линии 

### Скриншоты
![image](https://user-images.githubusercontent.com/52383546/229366072-6de5c2ef-46be-4c40-96dc-8128c7fa3bb2.png)

2023-04-03 09:27 UTC, ZinovNikita approved these changes
Единственное, хочу предложить написать, что сейчас рисует другой игрок
![image](https://user-images.githubusercontent.com/18033991/229469259-0ffbba5b-a170-4b42-b75d-c8e43aee1392.png)

2023-04-04 02:12 UTC, Vladimir556 approved these changes

2023-04-04 07:06 UTC, Brarion requested changes
Немного не понял историю с рефами

2023-04-04 07:06 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +  const timeOutGame = useRef<ReturnType<typeof setTimeout> | null>(null)
А почему таймаут сделан в виде рефа?

2023-04-04 07:06 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
>    }, [seconds, webSocket, timerActive])
Тут же можно сделать вот такое:
```tsx
  useEffect(() => {
    let timeout: NodeJS.Timeout | undefined;
    
    if (webSocket !== undefined && timerActive) {
      if (seconds > 0) {
        timeout = setTimeout(setSeconds, 1000, seconds - 1)
      } else if (lead === currentUser?.id) {
        setToastText("Вы не успели, переход хода")
        setShowToast(true)
        webSocket!.sendContent('clear', {})
        setLeadingPlayer(nextPlayer[0].id)
      }
    }
    return () => {
      if (timeout) {
        clearTimeout(timeout)
      }
    }
  }, [seconds, webSocket, timerActive])
  ```

2023-04-04 07:06 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +        )
Аналогично, странно делать реф на это, просто реф обычно – это ссылка на узел DOM дерева

2023-04-05 10:15 UTC, CyberDasein commented on packages/client/src/pages/game/Game.tsx
> +        )
@Brarion , да с рефами перемудрил, сейчас исправил

2023-04-05 19:17 UTC, Brarion approved these changes

2023-04-05 19:17 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
>    const [lead, setLeading] = useState<number>()
`number`, но начальное значение `undefined`?

2023-04-06 08:36 UTC, merged