feature/22-43 OAuth переносим на сервер
22-team-007/game-crocodile pull request #53
Opened 2023-04-07 14:16 UTC by sgp900

### Какую задачу решаем
1. Подключили мидлварю для проксирования api и ws
2. Добавлена возможность регистрироваться  в приложении с помощью OAuth. Перенесли механизм на сервер.

2023-04-07 23:56 UTC, ZinovNikita requested changes
ENV для хоста и порта и его использовать везде вместо localhost:3000

2023-04-07 23:56 UTC, ZinovNikita commented on packages/client/src/api/auth.test.ts
>      ])
лучше ENV определить какой-то для хоста, тк на серваке не будет это работать, и в докере тоже

2023-04-08 13:47 UTC, CyberDasein approved these changes

2023-04-09 17:17 UTC, ZinovNikita approved these changes

2023-04-10 09:10 UTC, Brarion approved these changes

2023-04-10 16:06 UTC, merged