Feature/22 19
22-team-007/game-crocodile pull request #6
Opened 2023-02-05 11:17 UTC by CyberDasein

### Какую задачу решаем

Верстка экрана с игрой, создание первоначальной структуры

2023-02-05 11:29 UTC, ZinovNikita requested changes
Проверь работу тестов. Проблема именно в настройке тестов. Поэтому я использовал index.scss все стили записал туда. Либо настроить конфиг для тестов, чтобы он воспринимал стили как стили, а не как код
![image](https://user-images.githubusercontent.com/18033991/216816026-cab4e46c-d6e1-45d5-8019-0c36978fe5f7.png)

2023-02-05 14:51 UTC, ZinovNikita approved these changes

2023-02-06 01:16 UTC, Vladimir556 approved these changes

2023-02-06 18:48 UTC, Brarion commented on packages/client/src/App.tsx
> +  return (
Стоит добавить отступ

2023-02-06 19:00 UTC, Brarion commented on packages/client/src/App.tsx
> +import Game from './pages/game/Game'
1. Лучше импорт стилей перенести в нижнюю часть импортов, библиотеки – в верхнюю, а всё остальное по середине. Также красивее будет, если 3 (или больше по своему желанию) блока будут разделены отступами
2. Будет лучше, если импорт будет выглядеть следующим образом:
```tsx
import { Game } from './pages'
```
Для этого необходимо в папке pages создать файл `index.ts`, внутри которого будет импорт и экспорт необходимых компонентов. Например:
```tsx
export { Game } from './pages'
```

или
```tsx
import { Game } from './pages'

export { Game }
```
Также для этого необходимо в папке pages/game добавить файл `index.ts`, внутри которого также будет экспорт в следующем виде:
```tsx
export { default as Game } from './Game'
```
Или
```tsx
import Game from './Game'

export { Game }
```

2023-02-06 19:03 UTC, Brarion commented on packages/client/src/pages/game/styles.scss
> +body {
В рамках всего этого файла
1. Лучше разделять селекторы отступами
2. `SCSS` умеет работать с вложенными селекторами, в некоторых местах это есть, а в некоторых – нет, странно немного

2023-02-06 19:03 UTC, Brarion commented on packages/client/src/pages/game/styles.scss
> +}
Для адаптивной вёрстки не очень хорошо задавать жёстко ширину и/или высоту

2023-02-06 19:04 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +import './styles.scss'
Отступы для красоты)

2023-02-06 19:04 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +  const messageHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
Отступы между функциями тоже добавят красоты и читаемости)

2023-02-06 19:06 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +            onMouseDown={() => mouseDownHandler()}
А почему не написать просто
```tsx
onMouseDown={mouseDownHandler}
```

2023-02-06 19:07 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +            height={650}></canvas>
1. Жёсткие высота и ширина не очень хорошо вяжутся с адаптивкой, но если такие значения подходят для вашего дизайна, то окей
2. Можно закрыть тег `canvas` без внутренней части, то есть вот так:
```tsx
<canvas />
```

2023-02-06 19:08 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +              {['player 1', 'player 2', 'player 3', 'player 4'].map(player => (
Временное решение неплохое, но лучше выносить константы либо в начало файла, либо в отдельный файл, например, в `constants.ts` рядом с текущим файлом

2023-02-06 19:09 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +    <Container style={{ maxWidth: '1024px' }}>
Все стили лучше держать в `.scss` файлах

2023-02-06 19:09 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +                  style={{ border: 'none' }}>
Все стили лучше держать в `.scss` файлах

2023-02-06 19:10 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +              {['message 1', 'message 2', 'message 3', 'message 4'].map(msg => (
Временное решение неплохое, но лучше выносить константы либо в начало файла, либо в отдельный файл, например, в `constants.ts` рядом с текущим файлом

2023-02-06 19:10 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +                  <span style={{ color: '#00a8f5' }}>player 1</span> {msg}
Все стили лучше держать в `.scss` файлах

2023-02-06 19:11 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +              </svg>
`SVG` лучше вынести отдельно в папку `assets` или `icons`, например, они могут занимать очень много строк

2023-02-06 19:12 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +export default memo(Game)
Не думаю, что здесь необходимо `memo`, потому что нет `props`, а родительский компонент не будет перерендериваться

2023-02-06 19:14 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +                  style={{ border: 'none' }}>
В `React` при использовании `.map` необходимо указывать проп `key`

2023-02-06 19:14 UTC, Brarion commented on packages/client/src/pages/game/Game.tsx
> +                </ListGroup.Item>
В `React` при использовании `.map` необходимо указывать проп `key`

2023-02-06 19:17 UTC, Brarion commented
Думаю, адаптивка не так планировалась выглядеть)

<img width="518" alt="Снимок экрана 2023-02-06 в 22 16 47" src="https://user-images.githubusercontent.com/54863186/217064187-68fc3b08-1f93-49b7-aba7-5c7a73030012.png">

2023-02-07 13:24 UTC, Brarion requested changes
Хорошо написано, но надо разобраться, не много ли 650 пикселей

2023-02-07 13:24 UTC, Brarion commented on packages/client/src/pages/game/index.tsx
> +  const mockPlayers = ['player 1', 'player 2', 'player 3', 'player 4']
Единственный минус такого описания констант – они будут создаваться снова каждый раз при каждом перерендере, который может произойти, если состоание `message` изменится
Поэтому, либо перенеси их лучше выше, над строкой 7:
 ```tsx
 const Game = () => {
 ```
 Либо вынеси в отдельный файл `constants.ts` в этой же папке `packages/client/src/pages/game`
 Либо используй мемоизацию с помощью `useMemo`, то есть вот так:
 ```tsx
  const mockMessages = useMemo(() => ['message 1', 'message 2', 'message 3', 'message 4'], [])
  const mockPlayers = useMemo(() => ['player 1', 'player 2', 'player 3', 'player 4'], [])
  ```
В последнем варианте из-за пустого массива (второй параметр) функция (первый параметр) вызовется всего лишь 1 раз в самом начале жизненного цикла компонента, в связи с чем массивы будут созданы 1 раз

2023-02-07 13:24 UTC, Brarion commented on packages/client/src/pages/game/index.tsx
> +            height={650}
А адаптивка есть же у вас? Просто телефоны же меньше 650 пикселей. Или на это пока не смотреть?)

2023-02-07 13:24 UTC, Brarion commented on packages/client/src/pages/game/index.tsx
> +                <ListGroup.Item key={index} className="d-flex justify-content-between text-white no-border">
Не советую использовать `index` для определения `key`, лучше взять `player`, они же тоже уникальные)

2023-02-07 13:24 UTC, Brarion commented on packages/client/src/pages/game/index.tsx
> +                <ListGroup.Item key={index}>
Аналогично, `index` не самое лучшее решение, но сообщения могут быть одинаковы, поэтому `msg` использовать тоже не хотелось бы... хм... ладно, оставим пока так, но будем помнить, что `index` – так себе)

2023-02-08 12:05 UTC, Brarion commented on packages/client/src/pages/game/index.tsx
> +            height={650}
Мне сказали, что адаптивка – не самое главное в проекте, поэтому оставляем 650)

2023-02-08 12:06 UTC, Brarion commented
> Хорошо написано, но надо разобраться, не много ли 650 пикселей

Отсутствие адаптивки – не критичная история, поэтому закроем глаза на 650 пикселей

2023-02-08 15:19 UTC, ZinovNikita commented on packages/client/src/pages/game/index.tsx
> +  const mockPlayers = ['player 1', 'player 2', 'player 3', 'player 4']
Ответ ЛК: компонент в данной задаче реализуется с незавершенным функционалом, это заглушка.
данный набор констант будет переделан в последующих реализациях игры, после внедрения API и внедрения Websocket API, так что принципиальной важности это замечание не имеет

2023-02-09 10:22 UTC, Brarion approved these changes
;)

2023-02-09 11:22 UTC, merged